apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: isa
spec:
  sourceRepos:
  - '*'
  destinations:
  - name: in-cluster
    namespace: isa-*
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'