apiVersion: v1
kind: Namespace
metadata:
  name: ipa-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: ipa-fancy-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ipa-fancy-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: ipa-ugly-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ipa-ugly-prod